### PR TITLE
ar: Require ReaderAt, provide SectionReader

### PR DESCRIPTION
**Pull request by charles-dyfis-net**
This is a breaking change: it drops support for non-seekable file streams and file-like interfaces that do not provide the ReaderAt interface.

In exchange for this loss of functionality, the `ar.Data` interfaces provided are now themselves seekable and rereadable, and still valid even after a subsequent portion of the same ar file has been consumed.

Similarly, it allows skipping over file content that does not need to be read.

### CODE REVIEW

**Comment by charles-dyfis-net** [comment]
This PR has admittedly grown substantially in scope -- I added debsig-style signature checking, as well as a refactor to take advantage of random access elsewhere in the process parsing (resulting in flatter code that stays to the left).

It is, of course, entirely your choice how much you want to take -- the PR's early commits are the less aggressive ones; I won't be the tiniest bit slighted if only a subset are adopted.

**Comment by paultag** [comment]
I am slightly sad to see the ability to consume an `io.Reader` go, but this seems like a reasonable reason to switch. I just started looking through the changeset, but at initial glance i don't think there'll be an issue to take the whole thing. I'll give this a full review now.

**Comment by paultag** [comment]
This is all a thoughtful and conscientious changeset. Nice work, @charles-dyfis-net

**Comment by paultag** [comment]
I've tagged this as v0.11.0 - thanks again!

**Pull request merged**
