### PR TITLE
Add a "Validate" method to the DSC type

### PR DESCRIPTION
**Pull request by tianon**
This will loop over all the `ChecksumsSha1`, `ChecksumsSha256`, and `Files` entries and run `Validate` on each of them.

### CODE REVIEW

**Comment by tianon** [comment]
plz be brutal in your review, kthx

**Comment by tianon** [comment]
What I _wanted_ to do, but Go won't let me, is just `for _, f := append(d.ChecksumsSha1, append(d.ChecksumsSha256, d.Files...)...) {`...

**Comment by tianon** [comment]
Actually, this would be a _lot_ simpler if we changed `hash.Validate()` to _only_ return `error`, and added a separate `IsValid` method for cases where you only want the boolean yes/no; thoughts before I go implementing that?

**Comment by paultag** [comment]
So, kinda really ugly, but I grok where it's coming from. Let me play with this for a sec

**Comment by paultag** [comment]
Yeah, good enough for now, thanks @tianon :dancer:

**Pull request merged**
