### PR TITLE
Add initial .travis.yml

### PR DESCRIPTION
**Pull request by tianon**
WIP; not sure if this will work as-is thanks to your vanity imports, but will get it sorted. :+1:

### CODE REVIEW

**Comment by tianon** [comment]
I _think_ our Go 1.5 error there will be fixed if we can get https://github.com/travis-ci/travis-build/pull/508, so I'd like to wait and see where that goes before I finish this if you don't mind @paultag. :heart:

**Comment by tianon** [comment]
Wooooot, my new Travis feature worked! :+1: :metal:

**Comment by meatballhat** [comment]
:metal: :smiley_cat:

**Comment by paultag** [comment]
:metal:

**Comment by paultag** [comment]
thanks @tianon and travisfolk!

**Pull request merged**
