### PR TITLE
declare a Go module

### PR DESCRIPTION
**Pull request by stapelberg**
related to #99

### CODE REVIEW

**Comment by paultag** [comment]
Thanks @stapelberg !

**Comment by paultag** [comment]
@stapelberg the only question I have is RE: the hashes in the import paths of deps. How do we update those semi-automatically? I don't like pinning as a general practice -- is that going to change the behavior of go-get or anything else?

**Comment by stapelberg** [comment]
Thanks to Minimum Version Selection, when building a binary, the latest version anything pulls in wins. So, if people are building things, they can force an update without us having to update — this isn’t pinning, it’s just specifying the minimums.

It’ll be sufficient to run “go get -u” when doing another change every once in a while (to cover the cases where users are even more tardy than we are) :)

**Comment by paultag** [comment]
flawless, thanks @stapelberg!

**Pull request merged**
