### PR TITLE
Ignore comment lines in paragraphs

### LINKED ISSUE #14: Can't handle comments in "debian/control"
Thanks to #13, I've tracked down the source of why I can't parse `debian/control` of `src:golang`:
```
Line "# DO NOT EDIT THIS FILE. EDIT debian/control.* instead!\n" is not 'key: val'
```

### PR DESCRIPTION
**Pull request by tianon**
Fixes #14

### CODE REVIEW

**Comment by paultag** [comment]
Euch. Could we add this as a reader or as part of the parser?

**Comment by paultag** [comment]
(My vote is part of the parser)

**Comment by tianon** [comment]
This is the parser, isn't it? (that's why I added it here)

**Comment by paultag** [comment]
Doh. You're right. Hurm.

**Comment by tianon** [comment]
Happy to move or refactor or rewrite, just need more to go on. :smile:

**Comment by paultag** [comment]
Can we do away with regex?:)

**Comment by tianon** [comment]
Yeah, sure!  I only used a regex because it could be trivially pre-compiled and will be superfast anyhow (especially since the regex engine is based on RE2), so the benefits of not using regex seemed small.  I'll go ahead and refactor without the regex. :+1:

**Comment by tianon** [comment]
Updated!

**Comment by tianon** [comment]
(Is this more what you had in mind?)

**Comment by paultag** [comment]
:+1: thanks!

**Comment by tianon** [comment]
:metal:

**Pull request merged**
