### PR TITLE
marshal

### PR DESCRIPTION
**Pull request by paultag**

### CODE REVIEW

**Comment by paultag** [comment]
god I hate this code

**Comment by paultag** [comment]
@tianon thoughts? Also all output is hella ugly

**Comment by tianon** [comment]
Do you have some sample output handy to illustrate what you mean?

**Comment by paultag** [comment]
```
(debian)[paultag@cassiel:~/dev/local/debian][⎇  paultag/feature/marshal] ♥  go run main.go 
Something: Joe,Sue
Other-Now: Foo
```

```go
package main

import (
	"bytes"
	"fmt"

	"pault.ag/go/debian/control"
)

type Testing struct {
	Something []string `delim:","`
	OtherNow  string   `control:"Other-Now"`
}

func main() {
	t := Testing{Something: []string{"Joe", "Sue"}, OtherNow: "Foo"}
	buf := bytes.Buffer{}
	control.Marshal(&t, &buf)
	fmt.Printf("%s\n", buf.String())
}
```

**Comment by paultag** [comment]
Note the ugly spacing on the `delim`'d field. Need a good solution to that.

**Comment by paultag** [comment]
Also would be good to have a good wrap-and-replace

**Comment by paultag** [comment]
(for Dependency and list fields)

**Comment by paultag** [comment]
meh. replacing this with a `String` method

**Comment by paultag** [comment]
Re-opening. I think I just need to make things less bad.

**Comment by tianon** [comment]
Ack, yeah, that's a challenging one.

**Comment by paultag** [comment]
overhauling the code to suck less

**Pull request closed without merging**
