### PR TITLE
Add a quick and dirty Debfile reader

### PR DESCRIPTION
**Pull request by paultag**

### CODE REVIEW

**Comment by paultag** [comment]
cc @tianon

**Comment by paultag** [comment]
```go
package main

import (
	"fmt"
	"io"

	"pault.ag/go/archive"
)

func main() {
	packages, err := archive.LoadPackages(
		"/home/paultag/tmp/infra/dists/unstable/main/binary-amd64/Packages",
	)
	if err != nil {
		panic(err)
	}

	for {
		next, err := packages.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			panic(err)
		}
		fmt.Printf("%s\n", next.Package)
	}
}
```

produces


```
debian-binary   
control.tar.gz  
data.tar.xz
```

**Comment by tianon** [comment]
Hahaha, hawt :+1:

**Comment by paultag** [comment]
@tianon LGTY?

**Comment by tianon** [comment]
LGTM :+1:

**Pull request merged**
