### PR TITLE
fix parsing dependencies without space between name and version

### PR DESCRIPTION
**Pull request by s-kostyaev**
This prevent errors during parsing some packages found in internet. For example I have an error with this file: https://code-industry.net/public/master-pdf-editor-5.9.50-1-qt5.x86_64.deb

### CODE REVIEW

**Comment by tyaps** [comment]
It is useful fix for packages, which have dependencies field like "foo(>= 1.0), bar(>= 1.0)" instead of commonly used format (with spaces between name and version) - "foo (>= 1.0), bar (>= 1.0)"
Such kind of packages installs as usual, all is ok, but this library returns an error while parsing. So this fix can handle them too.

**Comment by s-kostyaev** [comment]
@paultag do we have any chance for this to be merged?

**Comment by tyaps** [comment]
@paultag, please, reply if possible

**Comment by paultag** [comment]
Hey sorry my email is a train wreck recently. Thanks for this, totally a bug, thanks for the PR

**Pull request merged**
